version: '3.1'

services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
       - ./.env:/opt/app/.env
#    networks:
#      - back
#      - reverse-proxy
    depends_on:
      - pg_network1

  pg_network1:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT:-5432}:5432

#networks:
#  reverse-proxy:
#    external:
#      name: reverse-proxy
#  back:
#    driver: bridge
#
#volumes:
#  postgres:
