version: '3.1'

services:
  pg_network1:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
    ports:
      - ${POSTGRES_PORT:-5432}:5432
