version: '3.1'

services:
  backend:
    build: ../.
    ports:
      - 3000:3000
    volumes:
       - ./.env:/opt/app/.env
#    networks:
#      - back
#      - reverse-proxy
    depends_on:
      - pg_network1
      - rabbit-mq_1

  pg_network1:
    image: postgres
    restart: always
    env_file: ../.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  rabbit-mq_1:
    env_file: ../.env
    build: ./rabbit
    hostname: rabbit.dev
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-radmin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-123456}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-rabbitMq}
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
      RABBITMQ_LOG_BASE: /var/log/rabbitmq
      RABBITMQ_MNESIA_BASE: /var/lib/rabbitmq
      RABBITMQ_SCHEMA_DIR: /var/lib/rabbitmq
    volumes:
      - data:/var/lib/rabbitmq
      - dataLogs:/var/log/rabbitmq
    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "35197:35197"
#networks:
#  reverse-proxy:
#    external:
#      name: reverse-proxy
#  back:
#    driver: bridge
#
#volumes:
#  postgres:

volumes:
  data:
  dataLogs:
